# ====================================================
# Basic server setup
# ====================================================
---
- hosts: localhost
  vars:
    home: "{{role_path}}"
  tasks: 
    
    - name: Add 8.8.8.8 to resolv.conf to fix macvlan stuff
      lineinfile: path=/etc/resolv.conf
        insertbefore="^nameserver"
        line="nameserver 8.8.8.8"
      become: yes

    - name: install essential packages
      apt: 
        name:   
          - git
          - software-properties-common
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
        update_cache: yes
      become: yes

    - name: Install the gpg key for docker
      apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present
      become: yes

    - name: install docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
        state: present
      become: yes

    - name: Remove old docker
      apt: 
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent          
        update_cache: yes
      become: yes

    - name: Install docker
      apt: 
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io   
        update_cache: yes
      register: apt_status
      until: apt_status is success
      retries: 2
      delay: 5
      become: yes

    - name: install all packages
      apt: 
        name:
            - docker-compose
            - zoxide
            - rclone  
            - appstream
            - attr
            - linux-headers-$(uname -r)
            - linux-image-amd64
            - spl
            - kmod
            - zfsutils-linux
            - zfs-dkms 
            - zfs-zed
            - autoconf
            - automake
            - autopoint
            - autotools-dev
            - bind9-host
            - cgroupfs-mount
            - cmdtest
            - crda
            - discover
            - discover-data
            - dns-root-data
            - dnsmasq-base
            - dnsutils
            - doc-debian
            - emacsen-common
            - exfat-fuse
            - exfat-utils
            - exim4-base
            - exim4-config
            - exim4-daemon-light
            - fd-find
            - ffmpeg
            - fontconfig
            - fonts-dejavu-core
            - gdisk
            - hdparm
            - iw
            - kbd
            - keyboard-configuration
            - laptop-detect
            - locales
            - lsof
            - lz4
            - m4
            - mailutils
            - mailutils-common
            - make
            - man-db
            - mariadb-common
            - mdadm
            - modemmanager
            - mokutil
            - mysql-common
            - neovim
            - netcat-traditional
            - network-manager
            - nmap
            - nmap-common
            - os-prober
            - pciutils
            - picocom
            - pkg-config
            - plocate
            - powermgmt-base
            - ppp
            - protobuf-compiler
            - psmisc
            - python3
            - reportbug
            - ripgrep
            - rsync
            - runit-helper
            - screen
            - shim-signed-common
            - shim-unsigned
            - smartmontools
            - tdb-tools
            - tini
            - tmux
            - traceroute
            - udisks2
            - unattended-upgrades
            - unzip
            - wireless-regdb
            - x11-common
            - xclip
            - xkb-data
            - zsh
            - zsh-common
            - bat
            - g++
            - libncurses-dev
            - cargo
            - fzf  
        state: latest
        update_cache: yes
      become: yes

    # - name: Install vimplug
    #  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        
        #  - name: Download fzf
        #    git:
        #      repo: https://github.com/junegunn/fzf.git
        #      dest: /root/.fzf
        #      
        #  - name: Installing fzf
        #    shell: yes | /root/.fzf/install
          
    - name: Installing oh-my-zsh
      shell: yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
     
    - name: Install powerlevel10k theme
      git: 
        repo: https://github.com/romkatv/powerlevel10k.git 
        dest: "{{home}}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Install dust (not in pkg manager yet) and Ansible doesn't have cargo support
      shell: yes | sh -c "$(cargo install du-dust)" --unattended
      become: yes

    - git:
        repo: https://github.com/mobile-shell/mosh.git
        dest: "{{home}}/.mosh"
     
    - name: autogen mosh configure file
      command: ./autogen.sh
      args:
        chdir: "{{home}}/.mosh"

    - name: configure mosh build
      command: ./configure
      args:
        chdir: "{{home}}/.mosh"

    - name: Build mosh
      command: make
      args:
        chdir: "{{home}}/.mosh"

    - name: Install mosh
      command: make install
      args:
        chdir: "{{home}}/.mosh"
        become: yes  

    - name: Add github identity
      copy:
        dest: "{{home}}/.gitconfig"
        content: |
          [user]
            name = mcondren
            email = mcondren@gmail.com
      
    - name: Export zsh DOTFILE location system-wide
      lineinfile: dest=/etc/zsh/zshenv
                  regexp="^export"
                  line="export ZDOTDIR={{home}}/.config/zsh"
                  state=present
      become: yes
          
    - name: Copy .zshrc to $HOME
      copy:
        src: "/etc/zsh/zshenv"
        dest: "{{home}}/.zshenv"
      become: yes  
                  
    - name: Adding github key
      shell: |
        eval `ssh-agent -s`
        ssh-add $HOME/.ssh/github
        ssh-add $HOME/.ssh/id_rsa

    - name: Clone dotfiles repo
      git:
        repo: git@github.com:mcondren/dotfiles.git
        version: master
        dest: "{{home}}/dotfiles"
        key_file: "{{home}}/.ssh/github"
        accept_hostkey: yes
      # ssh-agent doesn't allow key to pass through remote sudo commands.
      become: no
      
    - name: Clone docker repo
      git:
        repo: git@github.com:mcondren/docker.git
        version: master
        dest: "{{home}}/docker"
        key_file: "{{home}}/.ssh/github"
        accept_hostkey: yes
      # ssh-agent doesn't allow key to pass through remote sudo commands.
      become: no
 
    - name: Set Crontab env variable for rclone/rsync
      cron:
        name: SSH_AUTH_SOCK
        env: yes
        job: /tmp/ssh-agent-root-cron
      become: yes  

    - name: Add weekly rclone backup job to crontab
      cron:
        name: "rclone backup"
        special_time: weekly
        job: "/usr/bin/rclone sync /backup/docker crypt:backup/docker" 
      become: yes

    - name: Add weekly zpool scrub to crontab
      cron:
        name: "zpool scrub"
        special_time: weekly
        job: "zpool scrub backup"
      become: yes

    - name: Upgrade all packages
      apt: upgrade=safe
      become: yes

  
  
